import os

ULTRASONIC_ENABLED  = False
LINE_TRACKER_ENABLED = True
CRANE_ENABLED       = True
DS4_ENABLED         = True

log_file = False

I2C_BUS = 1

PCA9685_SERVO_ADDR = 0x40
PCA9685_SERVO_FREQ = 50

OLED_I2C_ADDR = 0x3C
OLED_WIDTH    = 128
OLED_HEIGHT   = 64

MPU6050_ADDR = 0x68

MOTOR_A_EN  = 4
MOTOR_A_IN1 = 26
MOTOR_A_IN2 = 21
MOTOR_B_EN  = 17
MOTOR_B_IN1 = 27
MOTOR_B_IN2 = 18

SERVO_COUNT      = 7
SERVO_MIN_PULSE  = 500
SERVO_MAX_PULSE  = 2400
SERVO_INIT_ANGLE = 90

SERVO_STEERING   = 0
SERVO_CAM_PAN    = 1
SERVO_CAM_TILT   = 2
SERVO_CLAW_ARM   = 6
SERVO_CLAW_GRIP  = 5

SERVO_INIT_ANGLES = {
    0: 90,
    1: 90,
    2: 90,
    3: 90,
    4: 90,
    5: None,
    6: None,
}

CLAW_ARM_UP      = 10
CLAW_ARM_DOWN    = 120
CLAW_GRIP_OPEN   = 80
CLAW_GRIP_CLOSED = 150

BUZZER_PIN      = 24
BUZZER_PASSIVE  = True

ULTRASONIC_TRIGGER      = 11
ULTRASONIC_ECHO         = 8
ULTRASONIC_MAX_DISTANCE = 2.0

LED_COUNT     = 16
LED_BRIGHTNESS = 255

SWITCH_PINS = [6, 13]

LINE_LEFT_PIN   = 20
LINE_RIGHT_PIN  = 19

CAMERA_RESOLUTION      = (640, 480)
CAMERA_FPS             = 45
CAMERA_JPEG_QUALITY    = 80
CAMERA_FLIP_HORIZONTAL = False
CAMERA_FLIP_VERTICAL   = False

CV_LINE_POS_1        = 440
CV_LINE_POS_2        = 380
CV_LINE_THRESHOLD    = 80

CV_LINE_FOLLOW_SPEED       = 35
CV_LINE_FOLLOW_STEER_GAIN  = 0.8
CV_LINE_FOLLOW_SCAN_Y_RATIO = 0.7

VOICE_MODEL_PATH  = "/opt/sherpa-ncnn/model"
VOICE_ALSA_DEVICE = "default"
VOICE_OUTPUT_FILE = "/tmp/picarpro_voice.txt"

DS4_DEVICE_NAME      = "Wireless Controller"
DS4_DEADZONE         = 0.12
DS4_STEER_SENSITIVITY = 1.0
DS4_CAM_SENSITIVITY  = 0.3
DS4_HEARTBEAT_TIMEOUT = 10.0
DS4_WATCHDOG_INTERVAL = 3.0
DS4_READ_TIMEOUT      = 2.0

DS4_INVERT_LY        = True
DS4_INVERT_RY        = True
DS4_SPEED_MULT       = 1.4
DS4_CRANE_STEP       = 5
DS4_DRIFT_STEER_RANGE = 70
DS4_STEER_RANGE      = 60

WEBSOCKET_PORT = 8888
FLASK_PORT     = 5000

HOTSPOT_SSID     = "Adeept_Robot"
HOTSPOT_PASSWORD = "12345678"
HOTSPOT_IP       = "10.42.0.1"

SECRET_KEY = os.environ.get('PICARPRO_SECRET_KEY', 'picarpro')

STEER_MAP = {
    'forward': 90, 'backward': 90, 'left': 150, 'right': 30,
    'forward_left': 120, 'forward_right': 60,
    'backward_left': 120, 'backward_right': 60, 'stop': 90,
}

OLED_SCROLL_TEXT = "PiCar Pro v2 modded "

DEFAULT_SPEED    = 50
TURN_RADIUS_MIN = 0.2
TURN_RADIUS_MAX = 1.0
